editor:
  github_repo: undp/ssc
  url: "http://prose.io"
baseurl: ""
version: '1.2'
title: UNDP South South Cooperation
domain: "http://www.undp-ssc-mapping.org"
email: "js@ppls.io"
description: South-South Cooperation data
host: 0.0.0.0
exclude:
  - node_modules
  - Gulpfile.js
  - package.json
  - admin_scripts
  - ssc.paw
  - ssc.sublime-project
markdown: kramdown
collections:
  ssc_projects:
    output: true
prose:
  rooturl: _ssc_projects
  metadata:
    _ssc_projects:
      - name: open_project_id
        field:
          element: text
          label: Project ID from open.undp.org
      - name: project_title
        field:
          element: text
          label: Project title
      - name: project_objective
        field:
          element: text
          label: Project objective
      - name: project_link
        field:
          element: text
          label: Project page URL
      - name: undp_role_type
        field:
          element: multiselect
          label: UNDP engagement type
          placeholder: Choose action
          options:
            - name: Builder of capacities
              value: builder_of_capacities
            - name: Knowledge broker
              value: knowledge_broker
            - name: Facilitator of partnerships
              value: facilitator_of_partnerships
      - name: thematic_focus
        field:
          element: multiselect
          label: Thematic Focus
          placeholder: Select area(s) of focus
          options:
            - name: Sustainable development pathways
              value: sustainable_development_pathways
            - name: Resilience building
              value: resilience_building
            - name: Inclusive and effective democratic governance
              value: inclusive_and_effective_democratic_governance
      - name: territorial_focus
        field:
          element: multiselect
          label: Territorial focus
          placeholder: Select area(s) of focus
          options:
            - name: Middle Income Countries
              value: mic
            - name: Small Island Developing States
              value: sids
            - name: Fragile States
              value: fragile_states
            - name: Least Developed Countries
              value: ldc
            - name: High Income Countries
              value: hic
      - name: scale
        field:
          element: select
          label: Scale of operation
          placeholder: "National, regional or global"
          options:
            - name: Global
              value: global
            - name: Regional
              value: regional
            - name: National
              value: national
      - name: region
        field:
          element: multiselect
          label: Region
          placeholder: Select region
          options:
            - name: "Latin America & Caribbean"
              value: lac
            - name: Africa
              value: africa
            - name: "Asia & Pacific"
              value: asia_pacific
            - name: Arab States
              value: arab_states
            - name: "Europe & CIS"
              value: europe_cis
      - name: country
        field:
          element: multiselect
          label: "Project location (country, etc)"
          placeholder: Select location(s)
          options:
            - name: Aruba
              value: ABW
            - name: Afghanistan
              value: AFG
            - name: Angola
              value: AGO
            - name: Anguilla
              value: AIA
            - name: Albania
              value: ALB
            - name: Andorra
              value: AND
            - name: Netherlands Antilles
              value: ANT
            - name: United Arab Emirates
              value: ARE
            - name: Argentina
              value: ARG
            - name: Armenia
              value: ARM
            - name: American Samoa
              value: ASM
            - name: Antarctica
              value: ATA
            - name: French Southern and Antarctic Territories
              value: ATF
            - name: Antigua and Barbuda
              value: ATG
            - name: Australia
              value: AUS
            - name: Austria
              value: AUT
            - name: Azerbaijan
              value: AZE
            - name: Burundi
              value: BDI
            - name: Belgium
              value: BEL
            - name: Benin
              value: BEN
            - name: Burkina Faso
              value: BFA
            - name: Bangladesh
              value: BGD
            - name: Bulgaria
              value: BGR
            - name: Bahrain
              value: BHR
            - name: Bahamas
              value: BHS
            - name: Bosnia and Herzegovina
              value: BIH
            - name: Belarus
              value: BLR
            - name: Belize
              value: BLZ
            - name: Bermuda
              value: BMU
            - name: Bolivia (Plurinational State of)
              value: BOL
            - name: Brazil
              value: BRA
            - name: Barbados
              value: BRB
            - name: Brunei Darussalam
              value: BRN
            - name: Bhutan
              value: BTN
            - name: Bouvet Island
              value: BVT
            - name: Botswana
              value: BWA
            - name: Central African Republic
              value: CAF
            - name: Canada
              value: CAN
            - name: Cocos Islands
              value: CCK
            - name: Switzerland
              value: CHE
            - name: Chile
              value: CHL
            - name: China
              value: CHN
            - name: "CÃ´te d'Ivoire"
              value: CIV
            - name: Cameroon
              value: CMR
            - name: Democratic Republic of Congo
              value: COD
            - name: Republic of Congo
              value: COG
            - name: Cook Islands
              value: COK
            - name: Colombia
              value: COL
            - name: Comoros
              value: COM
            - name: Cape Verde
              value: CPV
            - name: Costa Rica
              value: CRI
            - name: Cuba
              value: CUB
            - name: Christmas Island
              value: CXR
            - name: Cayman Islands
              value: CYM
            - name: Cyprus
              value: CYP
            - name: Czech Republic
              value: CZE
            - name: Germany
              value: DEU
            - name: Djibouti
              value: DJI
            - name: Dominica
              value: DMA
            - name: Denmark
              value: DNK
            - name: Dominican Republic
              value: DOM
            - name: Algeria
              value: DZA
            - name: Ecuador
              value: ECU
            - name: Egypt
              value: EGY
            - name: Eritrea
              value: ERI
            - name: Western Sahara
              value: ESH
            - name: Spain
              value: ESP
            - name: Estonia
              value: EST
            - name: Ethiopia
              value: ETH
            - name: Finland
              value: FIN
            - name: Fiji
              value: FJI
            - name: Falkland Islands (Malvinas)
              value: FLK
            - name: France
              value: FRA
            - name: Faroe Islands
              value: FRO
            - name: Micronesia (Federated States of)
              value: FSM
            - name: Gabon
              value: GAB
            - name: United Kingdom
              value: GBR
            - name: Georgia
              value: GEO
            - name: Ghana
              value: GHA
            - name: Gibraltar
              value: GIB
            - name: Guinea
              value: GIN
            - name: Guadeloupe
              value: GLP
            - name: Gambia
              value: GMB
            - name: Guinea-Bissau
              value: GNB
            - name: Equatorial Guinea
              value: GNQ
            - name: Greece
              value: GRC
            - name: Grenada
              value: GRD
            - name: Greenland
              value: GRL
            - name: Guatemala
              value: GTM
            - name: French Guiana
              value: GUF
            - name: Guam
              value: GUM
            - name: Guyana
              value: GUY
            - name: "Hong Kong, China (SAR)"
              value: HKG
            - name: Heard Island and McDonald Islands
              value: HMD
            - name: Honduras
              value: HND
            - name: Croatia
              value: HRV
            - name: Haiti
              value: HTI
            - name: Hungary
              value: HUN
            - name: Indonesia
              value: IDN
            - name: Isle of Man
              value: IMY
            - name: India
              value: IND
            - name: British Indian Ocean Territory
              value: IOT
            - name: Ireland
              value: IRL
            - name: Iran (Islamic Republic of)
              value: IRN
            - name: Iraq
              value: IRQ
            - name: Iceland
              value: ISL
            - name: Israel
              value: ISR
            - name: Italy
              value: ITA
            - name: Jamaica
              value: JAM
            - name: Jordan
              value: JOR
            - name: Japan
              value: JPN
            - name: Kazakhstan
              value: KAZ
            - name: Kenya
              value: KEN
            - name: Kyrgyz Republic
              value: KGZ
            - name: Cambodia
              value: KHM
            - name: Kiribati
              value: KIR
            - name: Saint Kitts and Nevis
              value: KNA
            - name: Korea (Republic of)
              value: KOR
            - name: Kuwait
              value: KWT
            - name: "Lao People's Democratic Republic"
              value: LAO
            - name: Lebanon
              value: LBN
            - name: Liberia
              value: LBR
            - name: Libya
              value: LBY
            - name: Saint Lucia
              value: LCA
            - name: Liechtenstein
              value: LIE
            - name: Sri Lanka
              value: LKA
            - name: Lesotho
              value: LSO
            - name: Lithuania
              value: LTU
            - name: Luxembourg
              value: LUX
            - name: Latvia
              value: LVA
            - name: Macao
              value: MAC
            - name: Morocco
              value: MAR
            - name: Monaco
              value: MCO
            - name: Republic of Moldova
              value: MDA
            - name: Madagascar
              value: MDG
            - name: Maldives
              value: MDV
            - name: Mexico
              value: MEX
            - name: Marshall Islands
              value: MHL
            - name: Republic of Macedonia
              value: MKD
            - name: Mali
              value: MLI
            - name: Malta
              value: MLT
            - name: Myanmar
              value: MMR
            - name: Montenegro
              value: MNE
            - name: Mongolia
              value: MNG
            - name: Northern Mariana Islands
              value: MNP
            - name: Mozambique
              value: MOZ
            - name: Mauritania
              value: MRT
            - name: Montserrat
              value: MSR
            - name: Martinique
              value: MTQ
            - name: Mauritius
              value: MUS
            - name: Malawi
              value: MWI
            - name: Malaysia
              value: MYS
            - name: Mayotte
              value: MYT
            - name: Namibia
              value: NAM
            - name: New Caledonia
              value: NCL
            - name: Niger
              value: NER
            - name: Norfolk Island
              value: NFK
            - name: Nigeria
              value: NGA
            - name: Nicaragua
              value: NIC
            - name: Niue
              value: NIU
            - name: Netherlands
              value: NLD
            - name: Norway
              value: NOR
            - name: Nepal
              value: NPL
            - name: Nauru
              value: NRU
            - name: New Zealand
              value: NZL
            - name: Oman
              value: OMN
            - name: Pakistan
              value: PAK
            - name: Panama
              value: PAN
            - name: Pitcairn Island
              value: PCN
            - name: Peru
              value: PER
            - name: Philippines
              value: PHL
            - name: Palau
              value: PLW
            - name: Papua New Guinea
              value: PNG
            - name: Poland
              value: POL
            - name: Puerto Rico
              value: PRI
            - name: "Korea, Democratic People's Republic of"
              value: PRK
            - name: Portugal
              value: PRT
            - name: Paraguay
              value: PRY
            - name: French Polynesia
              value: PYF
            - name: Qatar
              value: QAT
            - name: Reunion
              value: REU
            - name: Romania
              value: ROU
            - name: Russian Federation
              value: RUS
            - name: Rwanda
              value: RWA
            - name: Saudi Arabia
              value: SAU
            - name: Sudan
              value: SDN
            - name: Senegal
              value: SEN
            - name: Singapore
              value: SGP
            - name: Svalbard and Jan Mayen Islands
              value: SJM
            - name: Solomon Islands
              value: SLB
            - name: Sierra Leone
              value: SLE
            - name: El Salvador
              value: SLV
            - name: San Marino
              value: SMR
            - name: Somalia
              value: SOM
            - name: Serbia
              value: SRB
            - name: Sao Tome and Principe
              value: STP
            - name: Suriname
              value: SUR
            - name: Slovenia
              value: SVN
            - name: Sweden
              value: SWE
            - name: Swaziland
              value: SWZ
            - name: Seychelles
              value: SYC
            - name: Syrian Arab Republic
              value: SYR
            - name: Turks and Caicos Islands
              value: TCA
            - name: Chad
              value: TCD
            - name: Togo
              value: TGO
            - name: Thailand
              value: THA
            - name: Tajikistan
              value: TJK
            - name: Tokelau
              value: TKL
            - name: Turkmenistan
              value: TKM
            - name: Timor-Leste
              value: TLS
            - name: Tonga
              value: TON
            - name: Trinidad and Tobago
              value: TTO
            - name: Tunisia
              value: TUN
            - name: Turkey
              value: TUR
            - name: Tuvalu
              value: TUV
            - name: Taiwan
              value: TWN
            - name: Tanzania (United Republic of)
              value: TZA
            - name: Uganda
              value: UGA
            - name: Ukraine
              value: UKR
            - name: Uruguay
              value: URY
            - name: United States
              value: USA
            - name: Uzbekistan
              value: UZB
            - name: Holy See
              value: VAT
            - name: Saint Vincent and the Grenadines
              value: VCT
            - name: Venezuela (Bolivarian Republic of)
              value: VEN
            - name: British Virgin Islands
              value: VGB
            - name: United States Virgin Island
              value: VIR
            - name: Viet Nam
              value: VNM
            - name: Vanuatu
              value: VUT
            - name: Samoa
              value: WSM
            - name: Yemen
              value: YEM
            - name: South Africa
              value: ZAF
            - name: Zambia
              value: ZMB
            - name: Zimbabwe
              value: ZWE
            - name: Kosovo (SCR 1244)
              value: KOS
            - name: South Sudan
              value: SSD
            - name: Slovak Republic
              value: SVK
      - name: partner_type
        field:
          element: multiselect
          label: Partner types
          options:
            - name: International cooperation / development agencies
              value: international_cooperation_development_agencies
            - name: Regional / Inter-governmental organizations
              value: regional_inter_governmental_organizations
            - name: National governments
              value: national_governments
            - name: Sub-national governments
              value: sub_national_governments
            - name: CSO
              value: cso
            - name: Academia
              value: academia
            - name: Private sector
              value: private_sector
