# Site settings
baseurl: 
title: SSC Testing data
email: js@ppls.io
description: > # South-South Cooperation data

# Build settings
markdown: kramdown

collections:
  ssc_data:
    output: true

prose:
  rooturl: '_ssc_data'
  metadata:
    _ssc_data:
      - name: "thematic-focus"
        field:
          element: "multiselect"
          label: "Thematic Focus"
          placeholder: "Select area(s) of focus"
          options:
            - name: "Sustainable development"
              value: "sustainable-development,"
            - name: "Resilience building"
              value: "resilience-building,"
            - name: "Inclusive and effective democratic governance"
              value: "democratic-governance,"
      - name: "type"
        field:
          element: "multiselect"
          label: "Type of action"
          placeholder: "Choose action"
          options:
            - name: "Not set"
              value: null
            - name: "Capacity Building"
              value: "cap"
            - name: "Knowledge broker"
              value: "kno"
            - name: "Partnership facilitator"
              value: "par"
      - name: "location"
        field:
          element: "multiselect"
          label: "Location (country, etc)"
          placeholder: "Select location(s)"
          options:
            - name: "Angola"
              value: "AGO"
            - name: "Algeria"
              value: "DZA"
            - name: "Egypt"
              value: "EGY"
            - name: "Bangladesh"
              value: "BGD"
            - name: "Namibia"
              value: "NAM"
            - name: "Bulgaria"
              value: "BGR"
            - name: "Bolivia (Plurinational State of)"
              value: "BOL"
            - name: "Ghana"
              value: "GHA"
            - name: "Pakistan"
              value: "PAK"
            - name: "Prog for Palestinian People"
              value: "PAL"
            - name: "Cape Verde"
              value: "CPV"
            - name: "Honduras"
              value: "HND"
            - name: "Jordan"
              value: "JOR"
            - name: "Liberia"
              value: "LBR"
            - name: "Libyan Arab Jamahiriya"
              value: "LBY"
            - name: "Malaysia"
              value: "MYS"
            - name: "Korea, Democratic People's Republic of"
              value: "PRK"
            - name: "Tanzania (United Republic of)"
              value: "TZA"
            - name: "Botswana"
              value: "BWA"
            - name: "Cambodia"
              value: "KHM"
            - name: "Trinidad and Tobago"
              value: "TTO"
            - name: "Paraguay"
              value: "PRY"
            - name: "UN Capital Development  Fund"
              value: "H59"
            - name: "Saudi Arabia"
              value: "SAU"
            - name: "Lebanon"
              value: "LBN"
            - name: "Burkina Faso"
              value: "BFA"
            - name: "Bratislava Regional Center"
              value: "SVK"
            - name: "Mauritania"
              value: "MRT"
            - name: "Croatia"
              value: "HRV"
            - name: "Chile"
              value: "CHL"
            - name: "China"
              value: "CHN"
            - name: "Micronesia (Federated States of)"
              value: "FSM"
            - name: "Jamaica"
              value: "JAM"
            - name: "Peru"
              value: "PER"
            - name: "Djibouti"
              value: "DJI"
            - name: "Guinea"
              value: "GIN"
            - name: "Uruguay"
              value: "URY"
            - name: "Thailand"
              value: "THA"
            - name: "Seychelles"
              value: "SYC"
            - name: "Nepal"
              value: "NPL"
            - name: "Morocco"
              value: "MAR"
            - name: "Yemen"
              value: "YEM"
            - name: "Philippines"
              value: "PHL"
            - name: "South Africa"
              value: "ZAF"
            - name: "Kiribati"
              value: "KIR"
            - name: "Romania"
              value: "ROU"
            - name: "Syrian Arab Republic"
              value: "SYR"
            - name: "Nicaragua"
              value: "NIC"
            - name: "Kazakhstan"
              value: "KAZ"
            - name: "PB/South Korea Liaison Office"
              value: "H62"
            - name: "Niue"
              value: "NIU"
            - name: "Dominica"
              value: "DMA"
            - name: "Benin"
              value: "BEN"
            - name: "Nigeria"
              value: "NGA"
            - name: "Reg Bur Latin Amer & Carib"
              value: "H03"
            - name: "Reg Bureau for Africa"
              value: "H01"
            - name: "Zimbabwe"
              value: "ZWE"
            - name: "Reg Bur for Arab States"
              value: "H05"
            - name: "Sri Lanka"
              value: "LKA"
            - name: "Guyana"
              value: "GUY"
            - name: "Costa Rica"
              value: "CRI"
            - name: "Ethiopia"
              value: "ETH"
            - name: "Dakar Regional Service Centre"
              value: "R11"
            - name: "Niger"
              value: "NER"
            - name: "Tokelau"
              value: "TKL"
            - name: "Turkmenistan"
              value: "TKM"
            - name: "Suriname"
              value: "SUR"
            - name: "Panama"
              value: "PAN"
            - name: "Chad"
              value: "TCD"
            - name: "Georgia"
              value: "GEO"
            - name: "Montenegro"
              value: "MNE"
            - name: "Mongolia"
              value: "MNG"
            - name: "Office of Human Resources"
              value: "H18"
            - name: "Marshall Islands"
              value: "MHL"
            - name: "Office of the Administrator"
              value: "H13"
            - name: "Belize"
              value: "BLZ"
            - name: "BCPR"
              value: "H10"
            - name: "Evaluation Office"
              value: "H11"
            - name: "Afghanistan"
              value: "AFG"
            - name: "Burundi"
              value: "BDI"
            - name: "Belarus"
              value: "BLR"
            - name: "Grenada"
              value: "GRD"
            - name: "Rwanda"
              value: "RWA"
            - name: "Argentina"
              value: "ARG"
            - name: "Pacific Centre (PC)"
              value: "PSC"
            - name: "Tajikistan"
              value: "TJK"
            - name: "Haiti"
              value: "HTI"
            - name: "Mexico"
              value: "MEX"
            - name: "Saint Lucia"
              value: "LCA"
            - name: "India"
              value: "IND"
            - name: "Latvia"
              value: "LVA"
            - name: "Bhutan"
              value: "BTN"
            - name: "Saint Vincent and the Grenadines"
              value: "VCT"
            - name: "Viet Nam"
              value: "VNM"
            - name: "Antigua and Barbuda"
              value: "ATG"
            - name: "Fiji"
              value: "FJI"
            - name: "PB/Liaison/Copenhagen"
              value: "H28"
            - name: "Mauritius"
              value: "MUS"
            - name: "Dominican Republic"
              value: "DOM"
            - name: "PB/Liaison/Tokyo"
              value: "H25"
            - name: "PB/Liaison/Geneva"
              value: "H24"
            - name: "PB/Liaison/Brussels"
              value: "H27"
            - name: "Bureau for Dev. Policy"
              value: "H21"
            - name: "Operations Support Group"
              value: "H20"
            - name: "PB"
              value: "H23"
            - name: "BOM/Ofc of Asst Administrator"
              value: "H22"
            - name: "Indonesia"
              value: "IDN"
            - name: "Vanuatu"
              value: "VUT"
            - name: "Equatorial Guinea"
              value: "GNQ"
            - name: "Democratic Republic of Congo"
              value: "COD"
            - name: "Republic of Congo"
              value: "COG"
            - name: "Gabon"
              value: "GAB"
            - name: "Cook Islands"
              value: "COK"
            - name: "Comoros"
              value: "COM"
            - name: "Colombia"
              value: "COL"
            - name: "Nauru"
              value: "NRU"
            - name: "Moldova (Republic of)"
              value: "MDA"
            - name: "Madagascar"
              value: "MDG"
            - name: "Ecuador"
              value: "ECU"
            - name: "Senegal"
              value: "SEN"
            - name: "Maldives"
              value: "MDV"
            - name: "Timor-Leste"
              value: "TLS"
            - name: "Lithuania"
              value: "LTU"
            - name: "Mozambique"
              value: "MOZ"
            - name: "Zambia"
              value: "ZMB"
            - name: "Gambia"
              value: "GMB"
            - name: "Guatemala"
              value: "GTM"
            - name: "Ukraine"
              value: "UKR"
            - name: "Cuba"
              value: "CUB"
            - name: "Venezuela (Bolivarian Republic of)"
              value: "VEN"
            - name: "Reg Bureau for Asia & Pacific"
              value: "H04"
            - name: "Palau"
              value: "PLW"
            - name: "Kenya"
              value: "KEN"
            - name: "Lao People's Democratic Republic"
              value: "LAO"
            - name: "Turkey"
              value: "TUR"
            - name: "Albania"
              value: "ALB"
            - name: "Tuvalu"
              value: "TUV"
            - name: "Myanmar"
              value: "MMR"
            - name: "Cairo Regional Center"
              value: "R44"
            - name: "Panama Regional Center"
              value: "R46"
            - name: "Tunisia"
              value: "TUN"
            - name: "Russian Federation"
              value: "RUS"
            - name: "Rgnl Center in Bangkok (RCB)"
              value: "BRC"
            - name: "Barbados"
              value: "BRB"
            - name: "Brazil"
              value: "BRA"
            - name: "Serbia"
              value: "SRB"
            - name: "The former Yugoslav Republic of Macedonia"
              value: "MKD"
            - name: "Samoa"
              value: "WSM"
            - name: "Azerbaijan"
              value: "AZE"
            - name: "Guinea-Bissau"
              value: "GNB"
            - name: "Swaziland"
              value: "SWZ"
            - name: "Tonga"
              value: "TON"
            - name: "CÃ´te d'Ivoire"
              value: "CIV"
            - name: "Kosovo"
              value: "KOS"
            - name: "Korea (Republic of)"
              value: "KOR"
            - name: "Central African Republic"
              value: "CAF"
            - name: "Cyprus"
              value: "CYP"
            - name: "United Nations Volunteers"
              value: "UNV"
            - name: "Bosnia and Herzegovina"
              value: "BIH"
            - name: "Somalia"
              value: "SOM"
            - name: "Uzbekistan"
              value: "UZB"
            - name: "Cameroon"
              value: "CMR"
            - name: "Poland"
              value: "POL"
            - name: "Kuwait"
              value: "KWT"
            - name: "Eritrea"
              value: "ERI"
            - name: "Togo"
              value: "TGO"
            - name: "United Arab Emirates"
              value: "ARE"
            - name: "Malawi"
              value: "MWI"
            - name: "Iraq"
              value: "IRQ"
            - name: "El Salvador"
              value: "SLV"
            - name: "Mali"
              value: "MLI"
            - name: "Sao Tome and Principe"
              value: "STP"
            - name: "Iran (Islamic Republic of)"
              value: "IRN"
            - name: "South Sudan"
              value: "SSD"
            - name: "Sierra Leone"
              value: "SLE"
            - name: "Saint Kitts and Nevis"
              value: "KNA"
            - name: "Bahamas"
              value: "BHS"
            - name: "Solomon Islands"
              value: "SLB"
            - name: "Kyrgyz Republic"
              value: "KGZ"
            - name: "UN Developmt Coordination Unit"
              value: "H45"
            - name: "Uganda"
              value: "UGA"
            - name: "Human Development Report Ofc"
              value: "H43"
            - name: "Regional SC - Johannesburg"
              value: "RJB"
            - name: "Lesotho"
              value: "LSO"
            - name: "Spcl Unit for South South Coop"
              value: "H42"
            - name: "Sudan"
              value: "SDN"
            - name: "Bahrain"
              value: "BHR"
            - name: "Armenia"
              value: "ARM"
            - name: "Papua New Guinea"
              value: "PNG"
            - name: "Ofc of Info Systems&Technology"
              value: "H48"
      - name: "region"
        field:
          element: "multiselect"
          label: "Region"
          placeholder: "Select region"
          options:
            - name: "Latin America & Caribbean"
              value: "lac"
            - name: "Africa"
              value: "afr"
            - name: "Asia & Pacific"
              value: "asp"
            - name: "Arab States"
              value: "arb"
            - name: "Europe & CIS"
              value: "euc"
      - name: "partners"
        field:
          element: "multiselect"
          label: "Partner types"
          options:
            - name: "International cooperation / development agencies"
              value: "int"
            - name: "Regional / inter-governmental organizations"
              value: "reg"
            - name: "National governments"
              value: "nat"
            - name: "Sub-national governments"
              value: "sbn"
            - name: "Community Support Organisations"
              value: "cso"
            - name: "Academia"
              value: "acd"
            - name: "Private sector"
              value: "pvt"

